version: '2'
volumes:
    local-storage-db:
        external: true
    local-arquivosexternos-storage:
        external: true
    local-controlador-instalacao-storage:
        external: true
    local-volume-solr:
        external: true
    local-certs-storage:
        external: true
    local-fontes-storage:
        external: true
    local-openldap-slapd-storage:
        external: true
    local-openldap-db-storage:
        external: true

services:
    storage-app:
        image: "busybox:latest"
        labels:
            io.rancher.container.start_once: "true"
        volumes:
            - local-arquivosexternos-storage:/sei/arquivos_externos_sei/:rw
            - local-fontes-storage:/opt:rw
            - local-controlador-instalacao-storage:/sei/controlador-instalacoes
            - local-certs-storage:/sei/certs

    storage-certs:
        image: "busybox:latest"
        labels:
            io.rancher.container.start_once: "true"
        volumes:
            - local-certs-storage:/certs:rw
            
    storage-openldap:
        image: "busybox:latest"
        labels:
            io.rancher.container.start_once: "true"
        volumes:
            - local-openldap-slapd-storage:/etc/ldap/slapd.d
            - local-openldap-db-storage:/var/lib/ldap
            
    #ldapadmin: #serviceldap
    #    image: osixia/phpldapadmin:0.9.0 #serviceldap
    #    environment: #serviceldap
    #        - PHPLDAPADMIN_LDAP_CLIENT_TLS=false #serviceldap
    #        - PHPLDAPADMIN_LDAP_HOSTS=openldap #serviceldap
    #        - PHPLDAPADMIN_HTTPS=false #serviceldap
    #        - PHPLDAPADMIN_TRUST_PROXY_SSL=true #serviceldap
    #        - VIRTUAL_HOST=http://localhost/phpldapadmin*,https://localhost/phpldapadmin* #serviceldap
    #        - EXCLUDE_PORTS=443 #serviceldap
    #        - FORCE_SSL=true #serviceldap
    #    links: #serviceldap
    #        - openldap:openldap #serviceldap
    #openldap: #serviceldap
    #    image: processoeletronico/sei4-osixialdap1.2.2:1.0.0 #serviceldap
    #    environment: #serviceldap
    #        - KEEP_EXISTING_CONFIG=false #serviceldap
    #        - LDAP_ADMIN_PASSWORD=adminldap #serviceldap
    #        - LDAP_BACKEND=mdb #serviceldap
    #        - LDAP_BASE_DN= #serviceldap
    #        - LDAP_CONFIG_PASSWORD=configldap #serviceldap
    #        - LDAP_DOMAIN=pen.gov.br #serviceldap
    #        - LDAP_LOG_LEVEL=256 #serviceldap
    #        - LDAP_ORGANISATION=Processo Eletronico Nacional #serviceldap
    #        - LDAP_READONLY_USER=false #serviceldap
    #        - LDAP_REMOVE_CONFIG_AFTER_SETUP=true #serviceldap
    #        - LDAP_REPLICATION=false #serviceldap
    #        - LDAP_RFC2307BIS_SCHEMA=false #serviceldap
    #        - LDAP_SSL_HELPER_PREFIX=ldap #serviceldap
    #        - LDAP_TLS=false #serviceldap
    #    volumes_from: #serviceldap
    #        - storage-openldap #serviceldap
                
    jod: #servicejod
        image: processoeletronico/vagrant-sei4_jod #servicejod
    
    #mail: #servicemail
    #    image: processoeletronico/vagrant_sei4_mailcatcher #servicemail
    #    command: ["mailcatcher", "--no-quit", "--foreground", "--ip=0.0.0.0", "--smtp-port=25", "--http-port=80"] #servicemail
    #    expose: #servicemail
    #        - 25 #servicemail
    #        - 80 #servicemail
    #    environment: #servicemail
    #        - VIRTUAL_HOST=http://localhost/mailadmin*,https://localhost/mailadmin*,http://localhost/assets*,https://localhost/assets*,http://localhost/messages*,https://localhost/messages* #servicemail
    #        - FORCE_SSL=true #servicemail
    #        - EXCLUDE_PORTS=25,1080,1025 #servicemail
    #        - EXTRA_SETTINGS=http-request set-path "%[path\,regsub(^/mailadmin\,/)]" #servicemail
    
    memcached:
        image: memcached
    
    #memcachedadmin: #servicememcachedadmin
    #    image: processoeletronico/sei4-phpmemcachedadmin1.2.2:1.0.0 #servicememcachedadmin
    #    environment: #servicememcachedadmin
    #        - VIRTUAL_HOST=http://localhost/memcachedadmin*,https://localhost/memcachedadmin* #servicememcachedadmin
    #        - FORCE_SSL=true #servicememcachedadmin

    db:
        image: processoeletronico/sei4-mysql5.7:1.0
        labels:
            io.rancher.container.pull_image: always
            io.rancher.sidekicks: storage-db
        volumes:
            - local-storage-db:/var/lib/mysql
    
    #dbadmin: #servicedbadmin
    #    image: dockette/adminer:full #servicedbadmin
    #    environment: #servicedbadmin
    #        - VIRTUAL_HOST=http://localhost/dbadmin*,https://localhost/dbadmin* #servicedbadmin
    #        - FORCE_SSL=true #servicedbadmin
            
  
    solr:
        image: processoeletronico/sei4-solr8.2.0:1.0
        environment:
            - VIRTUAL_HOST=http://localhost/solr*,https://localhost/solr*
            - FORCE_SSL=true
        volumes:
            - local-volume-solr:/dados
        
    
    app-atualizador:
        image: processoeletronico/sei4-app:1.4.1
        entrypoint: "/entrypoint-atualizador.sh"
        volumes_from:
            - storage-app
            - storage-certs
        volumes:
            - /sei/controlador-instalacoes
        labels:
            io.rancher.container.pull_image: always
            io.rancher.container.start_once: 'true'
        environment:
        - APP_PROTOCOLO=https
        - APP_HOST=localhost
        - APP_ORGAO=ME
        - APP_ORGAO_DESCRICAO=Orgao Processo Eletronico - MySql
        - APP_NOMECOMPLEMENTO=SEI - PEN - DTH
        - APP_MEMCACHED_HOST=memcached
        - APP_DB_TIPO=MySql
        - APP_DB_HOST=db
        - APP_DB_PORTA=3306
        - APP_DB_SIP_BASE=sip
        - APP_DB_SIP_USERNAME=sip_user
        - APP_DB_SIP_PASSWORD=sip_user
        - APP_DB_SEI_BASE=sei
        - APP_DB_SEI_USERNAME=sei_user
        - APP_DB_SEI_PASSWORD=sei_user
        - APP_DB_ROOT_USERNAME=root
        - APP_DB_ROOT_PASSWORD=root
        - APP_SIP_CHAVE_ACESSO=d27791b8b33226ca19662539e9eb77edf604bd61d7f51c28f1f6387bb8413d1d9f0960d5
        - APP_SEI_CHAVE_ACESSO=7babf862dd3c172174e8e81ae7559e81a11ba933a3ddbb979eb9e56bc7d424603179ff17
        - APP_SOLR_URL=http://solr:8983/solr
        - APP_SOLR_CORE_PROTOCOLOS=sei-protocolos
        - APP_SOLR_TEMPO_COMMIT_PROTOCOLOS=300
        - APP_SOLR_CORE_BASECONHECIMENTO=sei-bases-conhecimento
        - APP_SOLR_TEMPO_COMMIT_BASECONHECIMENTO=60
        - APP_SOLR_CORE_PUBLICACOES=sei-publicacoes
        - APP_SOLR_TEMPO_COMMIT_PUBLICACOES=60
        - APP_MAIL_TIPO=2 
        - APP_MAIL_SERVIDOR=mail
        - APP_MAIL_PORTA=25
        - APP_MAIL_CODIFICACAO=8bit 
        - APP_MAIL_MAXDESTINATARIOS=999 
        - APP_MAIL_MAXTAMANHOANEXOSMB=999 
        - APP_MAIL_SEGURANCA=
        - APP_MAIL_AUTENTICAR=
        - APP_MAIL_USUARIO=
        - APP_MAIL_SENHA=
        - APP_MAIL_PROTEGIDO=
        - OPENLDAP_PRESENTE=false
        - OPENLDAP_ADMIN_PASSWORD=adminldap
        - OPENLDAP_DESLIGAR_NO_ORGAO_0=false
        - MODULO_ESTATISTICAS_INSTALAR=true
        - MODULO_ESTATISTICAS_VERSAO=CompatibilidadeSEI4.0.0
        - MODULO_ESTATISTICAS_URL=https://estatistica.dev.processoeletronico.gov.br
        - MODULO_ESTATISTICAS_SIGLA=SEIPUBLICO
        - MODULO_ESTATISTICAS_CHAVE=seipublico
        - MODULO_WSSEI_INSTALAR=
        - MODULO_WSSEI_VERSAO=
        - MODULO_WSSEI_URL_NOTIFICACAO=
        - MODULO_WSSEI_ID_APP=
        - MODULO_WSSEI_CHAVE=
        - MODULO_RESPOSTA_INSTALAR=true
        - MODULO_RESPOSTA_VERSAO=1.1.0
        links:
        - db:db
        - memcached:memcached
        - solr:solr #servicesolr
        - jod:jod #servicejod
        #- openldap:openldap #serviceldap
    app:
        image: processoeletronico/sei4-app:1.4.1
        entrypoint: "/entrypoint.sh"
        #ports:
        #    - 80:80
        #    - 443:443
        volumes_from:
            - storage-app
            - storage-certs
        labels:
            io.rancher.container.pull_image: always
            io.rancher.sidekicks: storage-arquivosexternos,storage-fontes,app-atualizador    
        environment:
        - APP_PROTOCOLO=https
        - APP_HOST=localhost
        - APP_ORGAO=ME
        - APP_ORGAO_DESCRICAO=Orgao Processo Eletronico - MySql
        - APP_NOMECOMPLEMENTO=SEI - PEN - DTH
        - APP_MEMCACHED_HOST=memcached
        - APP_DB_TIPO=MySql
        - APP_DB_HOST=db
        - APP_DB_PORTA=3306
        - APP_DB_SIP_BASE=sip
        - APP_DB_SIP_USERNAME=sip_user
        - APP_DB_SIP_PASSWORD=sip_user
        - APP_DB_SEI_BASE=sei
        - APP_DB_SEI_USERNAME=sei_user
        - APP_DB_SEI_PASSWORD=sei_user
        - APP_DB_ROOT_USERNAME=root
        - APP_DB_ROOT_PASSWORD=root
        - APP_SIP_CHAVE_ACESSO=d27791b8b33226ca19662539e9eb77edf604bd61d7f51c28f1f6387bb8413d1d9f0960d5
        - APP_SEI_CHAVE_ACESSO=7babf862dd3c172174e8e81ae7559e81a11ba933a3ddbb979eb9e56bc7d424603179ff17
        - APP_SOLR_URL=http://solr:8983/solr
        - APP_SOLR_CORE_PROTOCOLOS=sei-protocolos
        - APP_SOLR_TEMPO_COMMIT_PROTOCOLOS=300
        - APP_SOLR_CORE_BASECONHECIMENTO=sei-bases-conhecimento
        - APP_SOLR_TEMPO_COMMIT_BASECONHECIMENTO=60
        - APP_SOLR_CORE_PUBLICACOES=sei-publicacoes
        - APP_SOLR_TEMPO_COMMIT_PUBLICACOES=60
        - APP_MAIL_TIPO=2 
        - APP_MAIL_SERVIDOR=mail
        - APP_MAIL_PORTA=25
        - APP_MAIL_CODIFICACAO=8bit 
        - APP_MAIL_MAXDESTINATARIOS=999 
        - APP_MAIL_MAXTAMANHOANEXOSMB=999 
        - APP_MAIL_SEGURANCA=
        - APP_MAIL_AUTENTICAR=
        - APP_MAIL_USUARIO=
        - APP_MAIL_SENHA=
        - APP_MAIL_PROTEGIDO=
        - OPENLDAP_PRESENTE=false
        - MODULO_ESTATISTICAS_INSTALAR=true
        - MODULO_ESTATISTICAS_VERSAO=CompatibilidadeSEI4.0.0
        - MODULO_ESTATISTICAS_URL=https://estatistica.dev.processoeletronico.gov.br
        - MODULO_ESTATISTICAS_SIGLA=SEIPUBLICO
        - MODULO_ESTATISTICAS_CHAVE=seipublico
        - MODULO_WSSEI_INSTALAR=
        - MODULO_WSSEI_VERSAO=
        - MODULO_WSSEI_URL_NOTIFICACAO=
        - MODULO_WSSEI_ID_APP=
        - MODULO_WSSEI_CHAVE=
        - MODULO_RESPOSTA_INSTALAR=true
        - MODULO_RESPOSTA_VERSAO=1.1.0
        - VIRTUAL_HOST=https://localhost/sei*,https://localhost/sip*,https://localhost/infra*,http://localhost/sei*,http://localhost/sip*,http://localhost/infra*
        #- EXCLUDE_PORTS=443
        - EXCLUDE_PORTS=80
        - EXTRA_ROUTE_SETTINGS=ssl verify none
        - COOKIE=SRV insert indirect nocache
        links:
        - db:db
        - memcached:memcached
        - solr:solr #servicesolr
        - jod:jod #servicejod
        #- openldap:openldap #serviceldap
    balanceador: #servicebal
        image: processoeletronico/sei4-haproxydc:1.0.0 #servicebal
        links: #servicebal
            - app #servicebal
            - solr #servicesolr #servicebal
    #        - mail #servicemail #servicebal
    #        - ldapadmin #serviceldap #servicebal
    #        - memcachedadmin #servicememcachedadmin #servicebal
    #        - dbadmin #servicedbadmin #servicebal
        environment: #servicebal
            - EXTRA_FRONTEND_SETTINGS_80=use_backend stats if { path_beg -i /haproxy }, acl is_root path -i /, redirect code 301 location http://localhost/sei/ if is_root #servicebal
            - EXTRA_FRONTEND_SETTINGS_443=use_backend stats if { path_beg -i /haproxy }, acl is_root path -i /, redirect code 301 location http://localhost/sei/ if is_root #servicebal
            - CERT_FOLDER=/certs #servicebal
        volumes_from: #servicebal
            - storage-certs #servicebal
        volumes: #servicebal
            - /var/run/docker.sock:/var/run/docker.sock #servicebal
        ports: #servicebal
            - 80:80 #servicebal
            - 443:443 #servicebal